/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import RelationActions from "../redux/actions/RelationActions";

// END IMPORT ACTIONS

/** APIs

* actionsRelation.create
*	@description CRUD ACTION create
*
* actionsRelation.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsUser.list
*	@description CRUD ACTION list
*
* actionsRelation.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class RelationEdit extends Component {
  // Init relation
  constructor(props) {
    super(props);
    this.state = {
      relation: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsRelation.loadRelation(this.props.match.params.id);
    }
    
    this.props.actionsUser.loadUserList();
  }

  // Insert props relation in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      relation: props.relation
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.relation._id) {
      this.props.actionsRelation.saveRelation(this.state.relation).then(data => {
        this.props.history.push("/relations/");
      });
    } else {
      this.props.actionsRelation.createRelation(this.state.relation).then(data => {
        this.props.history.push("/relations/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Relation Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          <FormControl fullWidth required
              {...(!this.state.relation.status && !this.state.relation.status
                ? { error: true }
                : {})}>
            <InputLabel shrink htmlFor="status">
              Status
            </InputLabel>
            <Select
              value={this.state.relation.status || ""}
              onChange={Utils.handleChangeSelect.bind(this, "relation")}
              inputProps={{
                id: "status",
                name: "status"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              <MenuItem value={"FOLLOW"}>FOLLOW</MenuItem>
              <MenuItem value={"FOLLOWING"}>FOLLOWING</MenuItem>
            </Select>
          </FormControl>
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m user with User */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="user">User</InputLabel>
            <Select
              multiple
              value={this.state.relation.user || []}
              onChange={Utils.handleChangeSelect.bind(this, "relation")}
              input={<Input id="user" name="user" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listUser && this.props.listUser.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.relation.user &&
                      this.state.relation.user.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/relations/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsRelation: bindActionCreators(RelationActions, dispatch),
  };
};

// Validate types
RelationEdit.propTypes = { 
  actionsRelation: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    relation: state.RelationEditReducer.relation,
    listUser: state.RelationEditReducer.listUser
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(RelationEdit);
