/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.wishbox.db.wishbox_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE PostBase PLEASE EDIT ../Post.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Post object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.wishbox.db.wishbox_db.entity.Post;

public class PostBase implements RowMapper<Post>{
	
	private Long _id;
	
	// Attributes
    private String contents;
    private Date createdAt;
    private Boolean isPublic;
    private String title;
    private Date updatedAt;
	
	// Relations createdBy
	private String createdBy;
	
	
	// Relations m:m tags
	private ArrayList<Long> tags;
	
	
	@Override
	public Post mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Post obj = new Post();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setContents(rs.getString("contents"));
			obj.setCreatedAt(rs.getDate("createdAt"));
			obj.setIsPublic(rs.getBoolean("isPublic"));
			obj.setTitle(rs.getString("title"));
			obj.setUpdatedAt(rs.getDate("updatedAt"));
			
        	
        	// Relations 1:m createdBy
			obj.setCreatedBy(rs.getString("createdBy"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getContents() {
		return contents;
	}


	public void setContents(String contents) {
		this.contents = contents;
	}
	public Date getCreatedAt() {
		return createdAt;
	}


	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Boolean getIsPublic() {
		return isPublic;
	}


	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}
	public String getTitle() {
		return title;
	}


	public void setTitle(String title) {
		this.title = title;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}


	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	
    
    // Relations 1:m createdBy
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
    
    
    
    
    // Relations m:m tags
	public ArrayList<Long> getTags() {
		return tags;
	}

	public void setTags(ArrayList<Long> tags) {
		this.tags = tags;
	}
	
	
	public static class Post_tags implements RowMapper<Post_tags>{
		
		private Long _id;
		
		// Relations
	
		private Long id_Post;
		private Long id_Tag;
				
		@Override
		public Post_tags mapRow(ResultSet rs, int rowNum) throws SQLException {
			
			Post_tags obj = new Post_tags();
			try {
				obj.set_id(rs.getLong("id"));
				obj.setId_Post(rs.getLong("id_Post"));
				obj.setId_Tag(rs.getLong("id_Tag"));
			}
			catch(Exception e) {
				e.printStackTrace();
			}
			return obj;
		}
		public Long get_id() {
			return _id;
		}
	
		public void set_id(Long _id) {
			this._id = _id;
		}
	
		public Long getId_Post() {
			return id_Post;
		}
	
	
		public void setId_Post(Long id_Post) {
			this.id_Post = id_Post;
		}
	
	
		public Long getId_Tag() {
			return id_Tag;
		}
	
	
		public void setId_Tag(Long id_Tag) {
			this.id_Tag = id_Tag;
		}
	}
    
}