/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.wishbox.db.wishbox_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE RelationBase PLEASE EDIT ../Relation.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Relation object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.wishbox.db.wishbox_db.entity.Relation;

public class RelationBase implements RowMapper<Relation>{
	
	private Long _id;
	
	// Attributes
    private Integer status;
	
	
	// Relations m:m user
	private ArrayList<Long> user;
	
	
	@Override
	public Relation mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Relation obj = new Relation();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setStatus(rs.getInt("status"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Integer getStatus() {
		return status;
	}


	public void setStatus(Integer status) {
		this.status = status;
	}
	
    
    
    
    
    // Relations m:m user
	public ArrayList<Long> getUser() {
		return user;
	}

	public void setUser(ArrayList<Long> user) {
		this.user = user;
	}
	
	
	public static class Relation_user implements RowMapper<Relation_user>{
		
		private Long _id;
		
		// Relations
	
		private Long id_Relation;
		private Long id_User;
				
		@Override
		public Relation_user mapRow(ResultSet rs, int rowNum) throws SQLException {
			
			Relation_user obj = new Relation_user();
			try {
				obj.set_id(rs.getLong("id"));
				obj.setId_Relation(rs.getLong("id_Relation"));
				obj.setId_User(rs.getLong("id_User"));
			}
			catch(Exception e) {
				e.printStackTrace();
			}
			return obj;
		}
		public Long get_id() {
			return _id;
		}
	
		public void set_id(Long _id) {
			this._id = _id;
		}
	
		public Long getId_Relation() {
			return id_Relation;
		}
	
	
		public void setId_Relation(Long id_Relation) {
			this.id_Relation = id_Relation;
		}
	
	
		public Long getId_User() {
			return id_User;
		}
	
	
		public void setId_User(Long id_User) {
			this.id_User = id_User;
		}
	}
    
}